# Generated by Django 3.2.5 on 2021-07-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_leavereportstaff_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
