# Generated by Django 3.2.5 on 2021-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_remove_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_date',
            field=models.CharField(max_length=255),
        ),
    ]
