# Generated by Django 3.2.5 on 2021-07-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_alter_leavereportstudent_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
