# Generated by Django 3.2.5 on 2021-09-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_auto_20210808_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fcm_token',
        ),
    ]
